<?php

namespace App\Livewire\JournalEntry;

use App\Models\ChartOfAccount;
use App\Services\JournalEntryService;
use App\Models\JournalEntry;
use Livewire\Component;
use Illuminate\Support\Facades\DB;

class JournalEntryForm extends Component
{
    public $date;
    public $reference; // Auto-generated by backend, but maybe show placeholder
    public $description;
    public $currency_code = 'USD';
    
    public $lines = [];
    public bool $isReadOnly = false;

    public ?JournalEntry $entry = null;

    protected $listeners = [
        'reset-journal-form' => 'resetForm',
        'load-journal-entry' => 'loadEntry',
        'start-create-entry' => 'startCreate',
    ];

    public function mount()
    {
        $this->resetForm();
    }

    public function resetForm()
    {
        $this->reset(['entry', 'date', 'reference', 'description', 'currency_code', 'lines', 'isReadOnly']);
        $this->date = now()->format('Y-m-d');
        $this->currency_code = 'USD';
        $this->lines = [];
        $this->addLine();
        $this->resetErrorBag();
    }

    public function startCreate()
    {
        $this->resetForm();
        $this->dispatch('open-journal-form-modal');
    }

    public function loadEntry($id, $readonly = false)
    {
        $this->resetForm();
        $this->isReadOnly = $readonly;
        $entry = JournalEntry::find($id);
        if ($entry) {
            $this->entry = $entry;
            $this->date = $entry->date->format('Y-m-d');
            $this->reference = $entry->reference;
            $this->description = $entry->description;
            $this->currency_code = $entry->currency_code;
            
            $this->lines = $entry->lines->map(function ($line) {
                return [
                    'account_id' => $line->account_id,
                    'description' => $line->description,
                    'debit' => (float) $line->debit,
                    'credit' => (float) $line->credit,
                ];
            })->toArray();
            
            $this->dispatch('open-journal-form-modal');
        }
    }

    public function addLine()
    {
        $this->lines[] = [
            'account_id' => '',
            'description' => '',
            'debit' => 0,
            'credit' => 0,
        ];
    }

    public function removeLine($index)
    {
        unset($this->lines[$index]);
        $this->lines = array_values($this->lines); // Re-index array
    }

    public function getTotalDebitProperty()
    {
        return collect($this->lines)->sum('debit');
    }

    public function getTotalCreditProperty()
    {
        return collect($this->lines)->sum('credit');
    }

    public function getIsBalancedProperty()
    {
        return abs($this->totalDebit - $this->totalCredit) < 0.0001;
    }

    public function save(JournalEntryService $service)
    {
        $this->validate([
            'date' => 'required|date',
            'lines' => 'required|array|min:1',
            'lines.*.account_id' => 'required|exists:chart_of_accounts,id',
            'lines.*.debit' => 'required|numeric|min:0',
            'lines.*.credit' => 'required|numeric|min:0',
        ]);

        if (!$this->isBalanced) {
            $this->dispatch('show-error', message: 'Debits must equal Credits.');
            return;
        }

        try {
            if ($this->entry) {
                $service->updateEntry($this->entry, [
                    'date' => $this->date,
                    'description' => $this->description,
                    'currency_code' => $this->currency_code,
                    'lines' => $this->lines,
                ]);
            } else {
                $service->createEntry([
                    'date' => $this->date,
                    'description' => $this->description,
                    'currency_code' => $this->currency_code,
                    'lines' => $this->lines,
                ]);
            }

            $this->dispatch('journal-entry-saved');

        } catch (\Exception $e) {
            $this->dispatch('show-error', message: $e->getMessage());
        }
    }

    public function render()
    {
        return view('livewire.journal-entry.journal-entry-form', [
            'accounts' => ChartOfAccount::orderBy('code')->get(),
        ]);
    }
}
